To: cavedeep@hotmail.com, BigD@DaveMorris.com, scotstoll@gmail.com, ktriand@gmail.com, rgkeyse@sandia.gov, jtriandafyllis73@gmail.com, wgb@buntonstudios.com, pardnerw@lumify.com, jbrady@exchange.calstatela.edu, smcohoon@gmail.com, brian@bkmcm.com, niratch@microsoft.com, marvin@linxdata.com, frogratty@gmail.com, cathywinfrey7@gmail.com, Arlie.Davis@microsoft.com, john@jfogarty.org, Erick.Smith@microsoft.com
Cc: johnhenryfogarty@gmail.com
Subject: 4th of July on the Slappey II
X-MID: 1048_N7JHF
X-Type: Email; Outmail
Date: 05 Jul 2014 04:34:25 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.HF.N7YRT
X-Date: 2014/07/05 04:34:26

Hello all,

Its the 4th of July and Mary and I are sitting snug in the Slappey, anchored amongst at least 100 other boats in Fisherman's Bay on Lopez Island waiting for the fireworks to start. This starts the first complete month of our new lives as full time cruising sailors.

We'll be headed down the coast to San Francisco in a couple of weeks, and we'll spend all of August there. Next we'll slowly work our way down to be in San Diego by November. After that Mexico... then the World. True if and only if we don't chicken out; sell the Slappey in San Francisco and move to where we never see the ocean again.

We've been having a wonderful time cruising about up here in the San Juans since the middle of last month, but now we're getting anxious to set out on the scary bit the Washington/Oregon coast.

Please wish us luck, 
  John and Mary
  Normal Email: svslappey@jfogarty.org
  SSB Email: n7jhf@winlink.org
  Blog: http://svslappey.wordpress.com/

P.S. This email was sent from N7JHF@WINLINK.ORG via our Single Sideband radio.
That means it was sent VERY VERY slowly. We can only accept similar emails that DO NOT CONTAIN ANY IMAGES; You can't imagine how slow the connection is.
