X-MID: 1053_N7JHF
To: "John Haller" <jh355mondial@yahoo.com>
Subject: Sorry we missed you in Pt Townsend
X-Type: Email; Outmail
Date: 07 Jul 2014 01:26:16 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.HF.KE7XO
X-Date: 2014/07/07 01:26:18

Hi John, Ruth and Anna,

We're sorry we didn't make it into Pt Townsend for the 4th. We've been all over up here in the San Juan's. Right now we're in little Bowman Bay for the night.  Tomorrow we'll tool over to PT for a rest and put together a few more things for our trip south. We hope to be on our way before the 15th.

Unfortunately due to our defunct inverter we haven't been able to charge our cell phones so we've been mostly incommunicado. Another tip is that when cell phones cannot find signal (in our case T-Mobile) they go dead really fast 'searching' for signal. I really need to add a little 75/100 watt job so we can charge little stuff an have a backup for the big one.

I just wanted to let you know how much we've appreciated your friendship and great advice during our years in PoE. We really hope to see y'all when you get out there.

I finally figured out how to send Email properly from the SSB.  If you get this is means I've succeeded.

Please wish us luck, 
  John and Mary
  Normal Email: svslappey@jfogarty.org
  SSB Email: n7jhf@winlink.org
  Blog: http://svslappey.wordpress.com/

P.S: This email was sent from N7JHF@WINLINK.ORG via our Single Sideband radio.
That means it was sent VERY VERY slowly. We can only accept similar emails that DO NOT CONTAIN ANY IMAGES; You can't imagine how slow the connection is.

P.P.S: Ruth! The ultra tough blue clips you gave us have been a godsend - they've been doing yeoman service drying everything from towels to unmentionables. It gives us the proper 'cruiser' look to have the boat half covered in laundry.
