X-In-Reply-To: 75JAUX3J1YNS
To: cathywinfrey7@gmail.com
Subject: Hi again - dead phone
X-MID: 1055_N7JHF
X-Type: Email; Outmail
Date: 07 Jul 2014 01:42:41 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.HF.KE7XO
X-Date: 2014/07/07 01:42:42

Hi Cathy!

I'm so sorry to hear about Soltano. We're so glad to hear that the others are doing well even if Edmund and Rosie aren't yet best bus with Toby.

On Rosie - I thought we told you - Rosie has benign hemangiomas (the red spots on her ears) and benign cysts on her tail and chin.  They come back and go away by themselves without you having to do anything.

My phone was almost totally discharged from a week without 115VAC - my inverter is on the fritz.  Hopefully I can charge it when we get to PT and call you tomorrow.

JF
