X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1058_N7JHF
X-Type: Radio; Outmail
Date: 09 Jul 2014 17:01:10 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2014/07/09 17:01:12

TIME: 2014/07/09 16:59
LATITUDE: 48-06.37N
LONGITUDE: 122-46.59W
COMMENT: Slappey at Boat Haven, Pt Townsend - final fitting out for going down the coast.
