X-In-Reply-To: 7I343160Z47C
To: KI7T
Subject: Re: //WL2K Hello from El Viajero
X-MID: 1059_N7JHF
X-Type: Radio; Outmail
Date: 09 Jul 2014 17:29:48 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2014/07/09 17:29:50

Hi John,

Fair Winds yourself. We're at Boat Haven in PT doing the final stuff. We'll head out the strait this weekend assuming the weather holds. 

Anytime you have a question about how we've buthchered the Slappey while fitting her out, don't hesitate to ask.  

JF
