X-In-Reply-To: SDKNT4ZQ25AV
To: "Cathy Winfrey" <cathywinfrey7@gmail.com>
Subject: Re: Position Report
X-MID: 1061_N7JHF
X-Type: Email; Outmail
Date: 13 Jul 2014 15:54:47 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2014/07/13 15:54:48

Hi!

The Slappey seems lonelier but no bigger to me.  We are bunking in the salon these days since on passage the V-berth is full of sails and the quarter-berth is full of stuff.  That makes it seem more like a tiny apartment since we can get out of bed without bumping our heads.

How are Edmund and Rosie reacting to Rufus these days?
JF
