To: "S/V Slappey Blog" <wage974nezi@post.wordpress.com>
Cc: "JF on GMail" <johnhenryfogarty@gmail.com>
Subject: A quick note by email....
X-MID: 1066_N7JHF
X-Type: Email; Outmail
Date: 18 Jul 2014 00:55:29 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2014/07/18 00:55:30

....as this will be the way we blog on our way down the Coast. We are now in Neah Bay, nearly the northwestern-most point of the (contiguous) U.S. Actually, just around the corner of a spit of land is Cape Flattery, which actually IS the northwestern-most bit of the Country. We spent 4 (long) days in Port Angeles waiting for weather, which calmed down by Wednesday, and headed out Juan de Fuca to the end. The Strait has been a challenge most of the way for us, showing us horrible chop, nasty swell, and of course, fog. We feel slightly more accomplished now, but only slightly. With any luck, we will be leaving on Saturday, bound for either Westport, or all the way to Newport, Oregon, depending on weather, seasickness and/or general anxiety levels. Until then, we can enjoy the beautiful scenery here in Neah Bay, on the Macah Reservation, which is having some rare sunny weather. Pictures to follow when wifi is more stable.

the crew of Slappey II
