To: "NOAA Weather Fax Email" <ftpmail@ftpmail.nws.noaa.gov>
Cc: "JF on GMail" <johnhenryfogarty@gmail.com>
Subject: Test of Weather Fax Fetching
X-MID: 1067_N7JHF
X-Type: Email; Outmail
Date: 19 Jul 2014 00:02:45 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2014/07/19 00:02:46

open
cd fax
get PYBA01.TIF
get PYBA05.GIF
get PPBE10.GIF
get PWBI10.GIF
get PWBM99.GIF
quit
