To: "S/V Slappey Blog" <wage974nezi@post.wordpress.com>
Cc: "JF on GMail" <johnhenryfogarty@gmail.com>
Subject: Enjoying Newport, OR..
X-MID: 1080_N7JHF
X-Type: Email; Outmail
Date: 24 Jul 2014 15:02:26 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2014/07/24 15:02:28

.....as well we should, as we'll likely be here for a week. Slappey doesn't do advisory winds and hazardous seas, on purpose. As a matter of fact, the window down the Coast to Newport was so benign, we had to motor for 55 out of 57 hours. Yes. We were as a trawler upon the seas; a very slow one. This did give us a chance to iron out the wrinkles of learning how to do longer passages, as well as night passages. The first night was terrifying, but the second one was (almost) fun for both of us. Neither of us got sick at all. The Yaquina (pronounced, "Yaqwinna," river bar was shrouded in fog, but otherwise baby-butt smoothe. The Port of Newport is inexpensive, and we've got an Aquarium, fresh seafood, beaches, museums....what's not to like? The downside is slow and crappy internet, thus..no pictures for now. You'll just have to trust us that it's pretty here. Next leg should start early next week, and hopefully will be another 2-day jaunt down to Crescent City, CA.
