X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1081_N7JHF
X-Type: Radio; Outmail
Date: 02 Aug 2014 05:16:55 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2014/08/02 05:16:56

TIME: 2014/08/02 05:14
LATITUDE: 44-37.43N
LONGITUDE: 124-03.13W
COMMENT: Still in Newport! We THINK we see a weather window opening up in a few days...; 
