X-MID: 1082_N7JHF
To: "Wout Beekhuizen-Brookhouse" <brookhouse@brookhouseonline.com>
Subject: Failed iMux
X-Type: Email; Outmail
Date: 03 Aug 2014 22:53:38 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2014/08/03 22:53:40

Hi Wout,

Thanks for the reply. I'll box the unit up and send it via EMS if possible when we get to Eureka in a few days. At that time, I'll give you an address in San Francisco to return it to, since we should be there for at least a month.

Thanks!
   John Fogarty - S/V Slappey II


>John,
>Sorry to hear that your iMux has failed. It sounds like the wifi module is the problem. Please send the unit back >to us, we will repair or replace under the one year warranty, but please note shipping costs are not covered by warranty.  Include a reference to this email conversation.
>Send by EMS or equivalent (priority international airmail), this is often just as quick and more economical than Fedex or UPS. Declare "electronics for repair", value $50.00.
>
>Address:
>Brookhouse
>PO Box 38-308
>Howick
>Auckland 2145
>New Zealand
>
>Wout Beekhuizen
>Brookhouse
>www.brookhouseonline.com
>36°54.46' S 174°57.23' E
