X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1087_N7JHF
X-Type: Radio; Outmail
Date: 06 Aug 2014 05:10:50 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2014/08/06 05:10:52

TIME: 2014/08/06 01:22
LATITUDE: 41-50.30N
LONGITUDE: 124-24.34W
COURSE: 210T
SPEED: 5.1
COMMENT: Next stop - Crescent City - good place to fix broken motor mount.; 
