To: "Wout Beekhuizen-Brookhouse" <brookhouse@brookhouseonline.com>
Cc: "John Fogarty" <johnhenryfogarty@gmail.com>, "John Fogarty" <john@jfogarty.org> 
Subject: Failed iMux is on its way to you
X-MID: 1089_N7JHF
X-Type: Email; Outmail
Date: 07 Aug 2014 19:42:11 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2014/08/07 19:42:12

Hello Again Wout,

I've shipped the iMux to you as requested.  
It was shipped USPS/EMS Priority Mail - 
  Label #: [EK39 5460 419U S]
  Customs Form #: CW925101999US
It should get there in a week or so.

Please return the unit to:
  Karen and Uri Cohen - Attn: John Fogarty
  2919 Prince Street
  Berkeley CA
  94705

I've included this info in the package.  If you need anything else from me (like more money) then call me at 512-589-5550 or email one or more of the attached addresses.

We're (slowly) working our way down the coast and should get to San Francisco (also Berkeley) in a couple of weeks.  We'll stay there at least 3 weeks so there should be plenty of time to get the repaired unit before we head further south.

Thanks!
   John Fogarty - S/V Slappey II
