X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1091_N7JHF
X-Type: Radio; Outmail
Date: 11 Aug 2014 09:20:37 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.HF.VE6GPS
X-Date: 2014/08/11 09:20:38

TIME: 2014/08/11 03:49
LATITUDE: 41-15.34N
LONGITUDE: 124-17.33W
COURSE: 193T
SPEED: 1.6
COMMENT: Bad S wind and waves. 2 knots - yuk. Plan B to Eureka.
