X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1099_N7JHF
X-Type: Radio; Outmail
Date: 14 Aug 2014 03:55:21 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.HF.KK5AN
X-Date: 2014/08/14 03:55:22

TIME: 2014/08/14 03:52
LATITUDE: 40-25.47N
LONGITUDE: 124-33.45W
COURSE: 148T
SPEED: 5.2
COMMENT: Whoo hoo! Past Cape Mendocino. We saw many many whales.
