X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1107_N7JHF
To: QTH
X-Type: Radio; Outmail
Subject: POSITION REPORT
Date: 18 Aug 2014 02:56:38 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.HF.K7DAV
X-Date: 2014/08/18 02:56:40

TIME: 2014/08/15 15:49
LATITUDE: 38-28.67N
LONGITUDE: 123-22.84W
COURSE: 137T
SPEED: 4.5
COMMENT: Heading in to Bodega Bay. Too slow for Drake's Bay by tonight.
