X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1122_N7JHF
X-Type: Radio; Outmail
Date: 28 Sep 2014 15:14:10 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2014/09/28 15:14:12

TIME: 2014/09/28 15:13
LATITUDE: 35-21.77N
LONGITUDE: 120-51.17W
COMMENT: Leaving Morro Bay for Santa Barbara. Should be there by tomorrow afternoon.
