X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1124_N7JHF
X-Type: Radio; Outmail
Date: 30 Sep 2014 23:03:14 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2014/09/30 23:03:16

TIME: 2014/09/30 23:02
LATITUDE: 34-24.30N
LONGITUDE: 119-41.44W
COMMENT: Happily tucked into Santa Barbara Harbor since yesterday; nice and warm here.
