X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1143_N7JHF
To: QTH
Subject: POSITION REPORT
X-Type: Radio; Outmail
Date: 30 Nov 2014 19:36:52 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2014/11/30 19:36:54

TIME: 2014/11/30 19:24
LATITUDE: 27-41.31N
LONGITUDE: 114-53.45W
COURSE: 193T
SPEED: 0.7
COMMENT: Safe and Sound in Turtle Bay - Seems charming from the boat...
