X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1145_N7JHF
X-Type: Radio; Outmail
Date: 04 Dec 2014 16:01:06 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.HF.W6IM
X-Date: 2014/12/04 16:01:08

TIME: 2014/12/04 15:54
LATITUDE: 26-16.37N
LONGITUDE: 113-49.41W
COURSE: 119T
SPEED: 4.3
COMMENT: Slappey in Sloppy Seas on the way to Bahia Santa Maria
