X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1147_N7JHF
X-Type: Radio; Outmail
Date: 05 Dec 2014 12:44:18 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.HF.KE7XO
X-Date: 2014/12/05 12:48:02

TIME: 2014/12/05 05:27
LATITUDE: 25-30.12N
LONGITUDE: 113-14.56W
COURSE: 163T
SPEED: 4.0
COMMENT: Slappey is out playing with the big boats. Furthest point from land for us.
