X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1152_N7JHF
X-Type: Radio; Outmail
Date: 09 Dec 2014 16:07:06 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.HF.KE7XO
X-Date: 2014/12/09 16:07:08

TIME: 2014/12/09 16:04
LATITUDE: 23-52.48N
LONGITUDE: 111-13.58W
COURSE: 130T
SPEED: 4.3
COMMENT: Crossing the Tropic of Cancer today! Steaming towards Cabo in calm seas.
