X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1154_N7JHF
X-Type: Radio; Outmail
Date: 16 Dec 2014 17:20:18 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.HF.XE2BNC
X-Date: 2014/12/16 17:20:20

TIME: 2014/12/16 16:59
LATITUDE: 23-02.11N
LONGITUDE: 108-10.05W
COURSE: 088T
SPEED: 4.8
COMMENT: About half way to Mazatlan. Rolly seas but easy going.
