X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1165_N7JHF
X-Type: Radio; Outmail
Date: 23 Feb 2015 00:12:10 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2015/02/23 00:12:12

TIME: 2015/02/23 00:10
LATITUDE: 19-35.05N
LONGITUDE: 105-07.86W
COMMENT: Anchored in beautiful Chamela - Finally, an easy trip with no surprise ending.
