X-In-Reply-To: 1581_AD6MH
To: AD6MH
Cc: svslappey@jfogarty.org
Subject: Re: Meet up?
X-MID: 1167_N7JHF
X-Type: Email; Outmail
Date: 28 Feb 2015 01:56:25 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2015/02/28 01:56:26

Nice to chat by radio earlier; we are in Paraiso tonight, which is about the nicest spot we've seen so far. We'll stay again tomorrow I think, and then probably head to Cuastecomate, and then Barra. Hope to see you there, or when we turn around and go to Tenacatita, maybe you'll still be there. 

Have fun!

John and Mary
