X-In-Reply-To: 1107_AD6MH
To: AD6MH
Subject: Re: Enjoy Tenacatita
X-MID: 1172_N7JHF
X-Type: Radio; Outmail
Date: 23 Mar 2015 12:59:32 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2015/03/23 12:59:34

Not very far yet; going to Chamela today, and then trucking all the way back to Mazatlan, to rest up to cross over to La Paz. Have a good trip back up. Visit Paraiso if you can. Say Hello to those Impulsive's; we enjoyed meeting them.

Mary C.
