X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1173_N7JHF
X-Type: Radio; Outmail
Date: 24 Mar 2015 00:06:52 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2015/03/24 00:06:54

TIME: 2015/03/24 00:06
LATITUDE: 19-33.54N
LONGITUDE: 105-06.58W
COMMENT: Lovely Isla Pajarera in Bahia Chamela. Tomorrow , north around Cabo Corrientes.
