X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1174_N7JHF
X-Type: Radio; Outmail
Date: 26 Mar 2015 23:19:20 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2015/03/26 23:19:22

TIME: 2015/03/26 23:18
LATITUDE: 23-16.11N
LONGITUDE: 106-27.85W
COMMENT: Could it be Mazatlan again???Sure enough, like a bad penney.... We're back!
