X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1175_N7JHF
X-Type: Radio; Outmail
Date: 02 Apr 2015 08:41:12 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.HF.K6IXA
X-Date: 2015/04/02 08:41:14

TIME: 2015/04/02 08:28
LATITUDE: 23-33.11N
LONGITUDE: 107-40.00W
COURSE: 279T
SPEED: 4.7
COMMENT: Crossing the Sea of Cortez to Los Muertos. Calm with a ring around the moon.
