X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1205_N7JHF
X-Type: Radio; Outmail
Date: 18 Jun 2015 22:28:46 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2015/06/18 22:28:48

TIME: 2015/06/18 22:27
LATITUDE: 26-01.03N
LONGITUDE: 111-09.86W
COMMENT: Anchored in the beautiful little cove of Puerto Ballandra. Still have Telcel!
