X-In-Reply-To: 2554_AD6MH
To: AD6MH
Subject: Re: when and where?
X-MID: 1219_N7JHF
X-Type: Radio; Outmail
Date: 08 Oct 2015 22:06:44 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2015/10/08 22:06:46

Scoots! Good to hear from you. We admire you hardy types. I don't think we'll be back in the sea, though, except from here to Mazatlan. Slappey is on the hard at the moment getting a few things done, plus a paint job. He should be back in the water in a couple of weeks, and we'll move back on by the end of Oct. He's likely staying in the water here in San Carlos for November, though, as we have some land travel to do; we go back to the States for our next visa, and then we'll make a trip to Mexico City and environs later in November. One of my nieces is in school there this semester, and her Mom (my sister) and family are meeting us up there, and will spend Thanksgiving there. We should be back here and headed south to Mazatlan by early December, I would think.  

What's up with you two, and where are you headed? Maybe you can swing by San Carlos?

PS:  I liked the song!

Cheers,

John and Mary
