X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1228_N7JHF
X-Type: Radio; Outmail
Date: 19 Mar 2016 02:37:40 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.HF.KE7XO
X-Date: 2016/03/19 02:37:42

TIME: 2016/03/19 01:29
LATITUDE: 24-26.47N
LONGITUDE: 110-18.66W
COMMENT: Play Bonanza, Isla Espiritu Santo - Tomorrow we start across the sea to Mazatlan
