X-To: QTH
Subject: POSITION REPORT
X-WL2K-Type: Position Report
X-Priority: 2
X-MID: 1230_N7JHF
X-Type: Radio; Outmail
Date: 22 Mar 2016 15:08:28 -0000
X-From: N7JHF
X-Status: Sent
X-Via: HAM.Telnet.WL2KW
X-Date: 2016/03/22 15:08:30

TIME: 2016/03/22 15:08
LATITUDE: 23-16.10N
LONGITUDE: 106-27.86W
COMMENT: Calm and rested at El Cid in Mazatlan - just waiting for our ship to come in.
